import colors from './colors';
import images from './images';

const constants = {
  /* serviceDefaultUrl: 'https://www.e-komobil.com/',
  newslink: 'https://www.e-komobil.com/m/news.php',
  utilityrateslink: 'https://www.e-komobil.com/m/pages.php?page=3',
  seatransportationlink: 'https://www.e-komobil.com/m/pages.php?page=14',
  transplanlink: 'https://www.e-komobil.com/m/pages.php?page=14',
  ferryhourslink: 'https://www.e-komobil.com/m/pages.php?page=4',
  trainhourslink: 'https://www.e-komobil.com/m/pages.php?page=5',
  frequentquestionslink: 'https://www.e-komobil.com/m/faq.php',
  driverinfolink: 'https://www.e-komobil.com/m/pages.php?page=12',
  ticketandtravelcardslink: 'https://www.e-komobil.com/m/pages.php?page=13',
  travelcardsofficeslink: 'https://www.e-komobil.com/m/pages.php?page=15',
  travelcardsregulationslink: 'https://www.e-komobil.com/m/pages.php?page=16',
  cardtypeslink: 'https://www.e-komobil.com/m/pages.php?page=17',
  cardrequestoperationslink: 'https://www.e-komobil.com/m/pages.php?page=18',
  lostpropertylink: 'https://www.e-komobil.com/m/pages.php?page=11',
  visaoperationslink: 'https://www.e-komobil.com/m/pages.php?page=20',
  chargingstationslink: 'https://www.e-komobil.com/m/dolum_noktalari.php',
  transruleslink: 'https://www.e-komobil.com/m/pages.php?page=9',
  servicestandartslink: 'https://www.e-komobil.com/m/pages.php?page=22',
  documentslink: 'https://www.e-komobil.com/m/documents.php',
  presidenttransmessagelink: 'https://www.e-komobil.com/m/pages.php?page=6',
  publictransportheadofdepartmentintroductionlink: 'https://www.e-komobil.com/m/pages.php?page=8',
  cityguidelink: 'http://rehber.kocaeli.bel.tr/',
  trafficdensitylink: 'https://www.e-komobil.com/m/trafficLayer.php',
  presidentmessagelink: 'https://www.e-komobil.com/m/pages.php?page=1',
  closedrouteslink: 'https://www.e-komobil.com/m/announcements.php?type=2',
  taxistationslink: 'https://www.e-komobil.com/m/taksi_duraklari.php',
  favouriteservice: 'https://www.e-komobil.com/services/servis_favori.php',

  kobisService: 'http://webservice.kobis.com.tr/?method=getstations',
  closestStopService: 'https://service.kentkart.com/ekomobilapi/stop/closest',
  newsservice: 'https://www.e-komobil.com/m/main_json.php',
  busTimesService: 'https://www.e-komobil.com/services/servis_hat_saatleri.php',
  ekomobilSearchRouteService: 'https://www.e-komobil.com/yolcu_bilgilendirme_operations.php',
  howtoGoSearchService: 'https://www.e-komobil.com/nasil_giderim_operations.php',
  server: 'https://service.kentkart.com',
  kentkartservice: 'https://service.kentkart.com/',
  kentkarttest: 'https://service.kentkart.com/test/',
  kentkarttripservice: 'https://service.kentkart.com/api/trip',
  SETTINGS_VERSION: 'IOS_1.0.0_10.3',
  SETTINGS_AUTH_TYPE: '4',
  SETTINGS_USER_ACCURACY: '0',
  LANGUAGE: 'tr',
  routeinfopath: '/ekomobilapi/route/info',
  closestbuslistpath: '/ekomobilapi/bus/closest',
  routedirectionpath: '/ekomobilapi/route/shape',
  checkbalancepath: '/ekomobilapi/card/balance',
  closestStopPath: '/ekomobilapi/stop/closest',
  routeShape: '/ekomobilapi/route/shape',
  kioskpath: '/ekomobilapi/kiosk',
  sha512key: '----XgDs3oGPvt9JwozOaEzQwKI5TdI52dfRwIDAQABsDgX----',
  tokenreccomp: 'X7tCHhH7nE99fBg',
  kocaeliregion: '004',
  latitude: '40.775986000000000000',
  longitude: '29.948356999999987000',

  searchrouteservice: 'https://service.kentkart.com/api/v2.0/route/list/',
  fetch_timeout: 20000, */
  /* UI CONSTANTS */
  headerColor: colors.headerColor,
  //menuIcon: images.iconMenu,
  //backIcon: images.iconBack,
};

module.exports = constants;
