/* export default {
  adult: 'e938',
  iconsettings: 'e612',

  //anasayfa iconları
  iconBus: 'e90b',

  // Sol Menü Ikonları
  iconhomepage: 'e620',
  iconpassengerinfo: 'e632',
  iconcloseststations: 'e61a',
  icontimetable: 'e637',
  icontimetable2: 'e611',
  iconferry: 'e81a',
  iconhowtogo: 'e90c',
  iconclosedroutes: 'e903',
  iconfavorites: 'e63a',
  iconcheckbalance: 'e615',
  iconsmartbike: 'e648',
  iconrecommendationcomplaint: 'e62b',
  iconlocation: 'e602',

  // Sağ Menü Ikonları
  iconnews: 'e61d',
  iconpromotionandbrochure: 'e63c',
  icontrafficdensity: 'e904',

  iconmenu: 'e62d',
  iconinfo: 'e608',
  iconpoint: 'e60f',
  iconpassengerinfohome: 'e603',
  iconsearch: 'e811',
  iconcloseststationshome: 'e90d',
  iconhowtogohome: 'e601',
  iconback: 'e626',
  iconaddtofav: 'e63b',
  iconremovetofav: 'e63a',
  arrow_up: 'e642',
  arrow_down: 'e619',
  button_arrow: 'e810',
  icondelete: 'e60c',
  iconbus: 'e60a',
  iconbus2: 'e609',
  iconbus3: 'e600',
  icontramway: 'e90a',
  icontaxi: 'e906',
  iconrefresh: 'e825',
  iconexpand: 'e989',
  iconlower: 'e98a',
  iconchange: 'e900',
  iconLocation: 'e624',
  iconFullRound: 'e60f',
  iconNullRound: 'e60e',
}; */
